#-------------------------------------------------------
# 製品環境
#-------------------------------------------------------
FROM httpd:2.4.58 as releaser

# 設定ファイルのコピー
COPY conf/httpd.conf /usr/local/apache2/conf/httpd.conf